import { AntdRegistry } from "@ant-design/nextjs-registry";
import StoreProvider from "./StoreProvider";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./cropper.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Magik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <AntdRegistry>
            <ConfigProvider>{children}</ConfigProvider>
          </AntdRegistry>
        </body>
      </html>
    </StoreProvider>
  );
}
